sudo: required
dist: trusty

services:
  - docker
  
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - ./larabit/vendor/laravel/dusk/bin/chromedriver-linux &
    - cp .env.testing .env
    - php artisan serve > /dev/null 2>&1 &

script:
    - php artisan dusk
