language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
before_install:
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer config repositories.AlbanMulaki vcs https://github.com/AlbanMulaki/LaraBit.git
  - composer update
  - cp ./vendor/AlbanMulaki/LaraBit/tests/config/.env ./
  - rm ./config/app.php
  - cp ./vendor/AlbanMulaki/LaraBit/tests/config/app.php ./config
  - php artisan vendor:publish
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - php artisan migrate
  - cd ./vendor/AlbanMulaki/LaraBit

script: "phpunit"
