language: php

php:
  - 5.6
  - 7.1
  - 7.2
matrix:
  allow_failures:
    - php: 7.2
  fast_finish: true
  include:
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable

sudo: required
dist: trusty

addons:
   chrome: stable

install:
   - cp larabit/.env.testing larabit/.env
   - travis_retry composer install -d larabit --no-interaction --prefer-dist --no-suggest

before_script:
   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
   - php larabit/artisan serve &

script:
   - php larabit/artisan dusk:install &
   - php larabit/artisan dusk
