version: '3'
services:
  web:
    hostname: web
    domainname: web.larabit
    build: .
    env_file:
    - ./larabit/.env
    ports:
    - "${APACHE_HTTP}:80"
    - "${APACHE_HTTPS}:443"
    volumes:
    - ${APP_DIR}:/var/www
    - ${APACHE_LOGS}:/var/log/httpd
    tty: true
    links:
    - "mysql:${MYSQL_HOSTNAME}"
  mysql:
    hostname: mysql
    domainname: mysql.larabit
    image: mariadb
    env_file:
    - ./larabit/.env
    ports:
    - "${MYSQL_PORT}:3306"
    env_file:
    - ${APP_DIR}/.env
